DROP TABLE PACU_BED;
DROP TABLE PACU_ROOM;
DROP TABLE OPERATION;
DROP TABLE OPERATION_TYPE;
DROP TABLE SURGEON;
DROP TABLE SPECIALTY;
DROP TABLE OPERATION_ROOM;
DROP TABLE PATIENT_ALLERGIES;
DROP TABLE ALLERGIES;
DROP TABLE PATIENT_MEDICATION;
DROP TABLE MEDICATION;
DROP TABLE PATIENT;

CREATE TABLE PATIENT(
PATIENT_ID INTEGER,
FIRST_NAME VARCHAR(40),
LAST_NAME VARCHAR(40),
GENDER CHAR,
BIRTHDATE DATE,
SOCIAL_SECURITY INTEGER,
ORGAN_DONOR BOOLEAN,
ADDRESS VARCHAR(100),
PHONE LONG,
PRIMARY KEY (PATIENT_ID)
);

CREATE TABLE MEDICATION(
MEDICATION_ID INTEGER,
MEDICATION_NAME VARCHAR(40),
PRIMARY KEY (MEDICATION_ID)
);

CREATE TABLE PATIENT_MEDICATION(
PATIENT_ID INTEGER,
MEDICATION_ID INTEGER,
DOSAGE INTEGER,
PRIMARY KEY (PATIENT_ID, MEDICATION_ID),
FOREIGN KEY(PATIENT_ID) REFERENCES PATIENT(PATIENT_ID),
FOREIGN KEY(MEDICATION_ID) REFERENCES MEDICATION(MEDICATION_ID)
);

CREATE TABLE ALLERGIES(
ALLERGIES_ID INTEGER,
ALLGERIES_NAME VARCHAR(40),
PRIMARY KEY (ALLERGIES_ID)
);

CREATE TABLE PATIENT_ALLERGIES(
PATIENT_ID INTEGER,
ALLERGIES_ID INTEGER,
DOSAGE INTEGER,
PRIMARY KEY (PATIENT_ID, ALLERGIES_ID),
FOREIGN KEY(PATIENT_ID) REFERENCES PATIENT(PATIENT_ID),
FOREIGN KEY(ALLERGIES_ID) REFERENCES ALLERGIES(ALLERGIES_ID)
);

CREATE TABLE OPERATION_ROOM(
OPERATION_ROOM_ID INTEGER,
ROOM_NUMBER INTEGER,
ROOM_TYPE VARCHAR(40),
ROOM_STATUS VARCHAR(20),
PRIMARY KEY (OPERATION_ROOM_ID)
);

CREATE TABLE SPECIALTY(
SPECIALTY_ID INTEGER,
SPECTIALY_NAME VARCHAR(40),
PRIMARY KEY (SPECIALTY_ID)
);

CREATE TABLE SURGEON(
SURGEON_ID INTEGER,
SPECIALTY_ID INTEGER,
FIRST_NAME VARCHAR(40),
LAST_NAME VARCHAR(40),
PRIMARY KEY (SURGEON_ID),
FOREIGN KEY (SPECIALTY_ID) REFERENCES SPECIALTY(SPECIALTY_ID)
);

CREATE TABLE OPERATION_TYPE(
OPERATION_TYPE_ID INTEGER,
OPERATION_NAME VARCHAR(40),
PRIMARY KEY (OPERATION_TYPE_ID)
);

CREATE TABLE OPERATION(
OPERATION_ID INTEGER,
OPERATION_ROOM_ID INTEGER,
OPERATION_TYPE_ID INTEGER,
PATIENT_ID INTEGER, 
SURGEON_ID INTEGER,
EXPECTED_START_TIME DATETIME,
ACTUAL_START_TIME DATETIME,
EXPECTED_FINISH_TIME DATETIME,
ACTUAL_FINISH_TIME DATETIME,
OPERATION_STATUS VARCHAR(40),
PRIMARY KEY (OPERATION_ID),
FOREIGN KEY (OPERATION_TYPE_ID) REFERENCES OPERATION_TYPE(OPERATION_TYPE_ID),
FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID),
FOREIGN KEY (SURGEON_ID) REFERENCES SURGEON(SURGEON_ID),
FOREIGN KEY (OPERATION_ROOM_ID) REFERENCES OPERATION_ROOM(OPERATION_ROOM_ID)
);

CREATE TABLE PACU_ROOM(
PACU_ROOM_ID INTEGER,
PACU_ROOM_NUMBER INTEGER,
PRIMARY KEY (PACU_ROOM_ID)
);

CREATE TABLE PACU_BED(
PACU_BED_ID INTEGER,
PACU_ROOM_ID INTEGER,
PATIENT_ID INTEGER,
PACU_BED_NUMBER INTEGER,
PACU_BED_STATUS VARCHAR(40),
PRIMARY KEY (PACU_BED_ID),
FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID),
FOREIGN KEY (PACU_ROOM_ID) REFERENCES PACU_ROOM(PACU_ROOM_ID)
);

/*INSERT INTO SURGEON(SURGEON_ID, FIRST_NAME, LAST_NAME)
VALUES(1, 'Nguyen', 'Doan');

INSERT INTO PATIENT(PATIENT_ID, FIRST_NAME, LAST_NAME)
VALUES(1, 'Adrian', 'Garcia');

INSERT INTO OPERATION_ROOM(OR_ID, ROOM)
VALUES(1, '234A');

INSERT INTO OPERATION(OPERATION_ID, OR_ID, PATIENT_ID, SURGEON_ID, START_TIME)
VALUES (1, 1, 1, 1, '2016-02-16 18:30:00');*/